bringify:
  jwtSecret: jDW3b3bYf
  jwtExpirationMs: 86400000

spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db-console
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)
    open-in-view: false
  sql:
    init:
      platform: h2
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: confirm.bringify@gmail.com
    password: sdmoadcrylropvha
    properties.mail.smtp:
      auth: true
      starttls.enable: true